source 'https://rubygems.org'
source 'http://10.0.3.15:9292'

gem 'aws-sdk'
gem 'shatterdome', '= 0.1.4'

gem 'rack'
gem 'sinatra-static'
gem 'sinatra-static-assets'
gem 'rack-flash3'
gem 'rack-flash-session'
gem 'easy_breadcrumbs'
gem 'dalli'
gem 'sinatra-dalli'
gem 'sinatra-session'
